# Generated by Django 2.2.5 on 2019-11-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchent_details',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('p_no', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('p_price', models.FloatField()),
                ('p_quantity', models.IntegerField()),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Merchent_details')),
            ],
        ),
    ]
