# Generated by Django 2.2.5 on 2019-11-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarchentModel',
            fields=[
                ('mrt_id', models.AutoField(primary_key=True, serialize=False)),
                ('mrt_name', models.CharField(max_length=30)),
                ('Email_id', models.EmailField(max_length=254)),
                ('contactNo', models.CharField(max_length=10)),
            ],
        ),
    ]
