# Generated by Django 2.2.5 on 2019-11-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchentmodel',
            name='password',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
