# Generated by Django 2.2.5 on 2019-11-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_marchentmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchentmodel',
            name='mrt_id',
            field=models.IntegerField(default=False, primary_key=True, serialize=False),
        ),
    ]
