# Generated by Django 2.2.5 on 2019-11-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsumerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumermodel',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
